import java.awt.Color;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author macbookpro
 */
public class GameFrame extends javax.swing.JFrame {
JButton[][] jb=new JButton[8][8];
Board b=new Board();
int color=-1;
boolean isvalid;
    /**
     * Creates new form GameFrame2
     */
    public GameFrame() {
        initComponents();
    }

    
    
    public static boolean have(ArrayList<Disk> list,Disk d){
    	for (int i=0;i<list.size();i++){
    		if(list.get(i).row==d.row&&list.get(i).col==d.col&&list.get(i).color==d.color)
    			return true;
    	}
    	return false;
    }
    
    

public static void printBoard(int[][] s){
	for(int i=0;i<s.length;i++){
		for(int j=0;j<s[i].length;j++){
			 System.out.printf("%5d",s[i][j]);
		}
		System.out.println();
	}
}


public static void printDisk(ArrayList<Disk> d){
if (d.isEmpty()){
System.out.println("NO valid move");	
}
else{
	for (int i=0;i<d.size();i++){
		System.out.println(d.get(i));
	}
}
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        b00 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        b03 = new javax.swing.JButton();
        b04 = new javax.swing.JButton();
        b05 = new javax.swing.JButton();
        b06 = new javax.swing.JButton();
        b07 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b45 = new javax.swing.JButton();
        b55 = new javax.swing.JButton();
        b65 = new javax.swing.JButton();
        b75 = new javax.swing.JButton();
       //74?
        b74 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b40 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b46 = new javax.swing.JButton();
        b50 = new javax.swing.JButton();
        b56 = new javax.swing.JButton();
        b60 = new javax.swing.JButton();
        b66 = new javax.swing.JButton();
        b70 = new javax.swing.JButton();
        b76 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b51 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b61 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b71 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();
        b47 = new javax.swing.JButton();
        b57 = new javax.swing.JButton();
        b67 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b77 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
       
        b52 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b62 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b72 = new javax.swing.JButton();
        b37 = new javax.swing.JButton();
       
        b12 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        b53 = new javax.swing.JButton();
        b63 = new javax.swing.JButton();
        b73 = new javax.swing.JButton();
       
        b13 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        b54 = new javax.swing.JButton();
        b64 = new javax.swing.JButton();
jb[0][0]=b00;
jb[0][1]=b01;
jb[0][2]=b02;
jb[0][3]=b03;
jb[0][4]=b04;
jb[0][5]=b05;
jb[0][6]=b06;
jb[0][7]=b07;

jb[1][0]=b10;
jb[1][1]=b11;
jb[1][2]=b12;
jb[1][3]=b13;
jb[1][4]=b14;
jb[1][5]=b15;
jb[1][6]=b16;
jb[1][7]=b17;

jb[2][0]=b20;
jb[2][1]=b21;
jb[2][2]=b22;
jb[2][3]=b23;
jb[2][4]=b24;
jb[2][5]=b25;
jb[2][6]=b26;
jb[2][7]=b27;

jb[3][0]=b30;
jb[3][1]=b31;
jb[3][2]=b32;
jb[3][3]=b33;
jb[3][4]=b34;
jb[3][5]=b35;
jb[3][6]=b36;
jb[3][7]=b37;

jb[4][0]=b40;
jb[4][1]=b41;
jb[4][2]=b42;
jb[4][3]=b43;
jb[4][4]=b44;
jb[4][5]=b45;
jb[4][6]=b46;
jb[4][7]=b47;

jb[5][0]=b50;
jb[5][1]=b51;
jb[5][2]=b52;
jb[5][3]=b53;
jb[5][4]=b54;
jb[5][5]=b55;
jb[5][6]=b56;
jb[5][7]=b57;

jb[6][0]=b60;
jb[6][1]=b61;
jb[6][2]=b62;
jb[6][3]=b63;
jb[6][4]=b64;
jb[6][5]=b65;
jb[6][6]=b66;
jb[6][7]=b67;

jb[7][0]=b70;
jb[7][1]=b71;
jb[7][2]=b72;
jb[7][3]=b73;
jb[7][4]=b74;
jb[7][5]=b75;
jb[7][6]=b76;
jb[7][7]=b77;


        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
/*
        b74.setLocation(new java.awt.Point(7, 4));
        b74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b74MouseClicked(evt);
            }
        });
*/
     
        for(int i=0;i<8;i++){
        	for(int j=0;j<8;j++){
        		final int row=i;
        		final int col=j;
        		jb[i][j].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        bMouseClicked(evt,row,col);
                    }
                });
        	}
        }
        b04.setLocation(new java.awt.Point(0, 4));
        b04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b04MouseClicked(evt);
            }
        });

        b14.setLocation(new java.awt.Point(1, 4));
        b14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b14MouseClicked(evt);
            }
        });

        b24.setLocation(new java.awt.Point(2, 4));
        b24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b24MouseClicked(evt);
            }
        });

        b34.setBackground(Color.black);
        b34.setLocation(new java.awt.Point(3, 4));
        b34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b34MouseClicked(evt);
            }
        });

        b45.setLocation(new java.awt.Point(4, 5));
        b45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b45MouseClicked(evt);
            }
        });

        b55.setLocation(new java.awt.Point(5, 5));
        b55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b55MouseClicked(evt);
            }
        });

        b65.setLocation(new java.awt.Point(6, 5));
        b65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b65MouseClicked(evt);
            }
        });

        b75.setLocation(new java.awt.Point(7, 5));
        b75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b75MouseClicked(evt);
            }
        });

       // b00.setForeground(new java.awt.Color(255, 0, 0));
        b00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b00MouseClicked(evt);
            }
        });

        b05.setLocation(new java.awt.Point(0, 5));
        b05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b05MouseClicked(evt);
            }
        });
        b05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b05ActionPerformed(evt);
            }
        });

        b10.setLocation(new java.awt.Point(1, 0));
        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b10MouseClicked(evt);
            }
        });

        b20.setLocation(new java.awt.Point(2, 0));
        b20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b20MouseClicked(evt);
            }
        });

        b30.setLocation(new java.awt.Point(3, 0));
        b30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b30MouseClicked(evt);
            }
        });

        b40.setLocation(new java.awt.Point(4, 0));
        b40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b40MouseClicked(evt);
            }
        });

        b15.setLocation(new java.awt.Point(1, 5));
        b15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b15MouseClicked(evt);
            }
        });

        b25.setLocation(new java.awt.Point(2, 5));
        b25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b25MouseClicked(evt);
            }
        });

        b35.setLocation(new java.awt.Point(3, 5));
        b35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b35MouseClicked(evt);
            }
        });

        b46.setLocation(new java.awt.Point(4, 6));
        b46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b46MouseClicked(evt);
            }
        });

        b50.setLocation(new java.awt.Point(5, 0));
        b50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b50MouseClicked(evt);
            }
        });

        b56.setLocation(new java.awt.Point(5, 6));
        b56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b56MouseClicked(evt);
            }
        });

        b60.setLocation(new java.awt.Point(6, 0));
        b60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b60MouseClicked(evt);
            }
        });

        b66.setLocation(new java.awt.Point(6, 6));
        b66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b66MouseClicked(evt);
            }
        });

        b70.setLocation(new java.awt.Point(7, 0));
        b70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b70MouseClicked(evt);
            }
        });

        b76.setLocation(new java.awt.Point(7, 6));
        b76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b76MouseClicked(evt);
            }
        });

        b41.setLocation(new java.awt.Point(4, 1));
        b41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b41MouseClicked(evt);
            }
        });

        b06.setLocation(new java.awt.Point(0, 6));
        b06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b06MouseClicked(evt);
            }
        });

        b51.setLocation(new java.awt.Point(5, 1));
        b51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b51MouseClicked(evt);
            }
        });

        b16.setLocation(new java.awt.Point(1, 6));
        b16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b16MouseClicked(evt);
            }
        });

        b61.setLocation(new java.awt.Point(6, 1));
        b61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b61MouseClicked(evt);
            }
        });

        b26.setSize(new java.awt.Dimension(2, 6));
        b26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b26MouseClicked(evt);
            }
        });

        b71.setLocation(new java.awt.Point(7, 1));
        b71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b71MouseClicked(evt);
            }
        });

        b01.setLocation(new java.awt.Point(0, 1));
        b01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b01MouseClicked(evt);
            }
        });

        b11.setLocation(new java.awt.Point(1, 1));
        b11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b11MouseClicked(evt);
            }
        });

        b21.setLocation(new java.awt.Point(2, 1));
        b21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b21MouseClicked(evt);
            }
        });

        b36.setLocation(new java.awt.Point(3, 6));
        b36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b36MouseClicked(evt);
            }
        });

        b47.setLocation(new java.awt.Point(4, 7));
        b47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b47MouseClicked(evt);
            }
        });

        b57.setLocation(new java.awt.Point(5, 7));
        b57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b57MouseClicked(evt);
            }
        });

        b67.setToolTipText("");
        b67.setLocation(new java.awt.Point(6, 7));
        b67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b67MouseClicked(evt);
            }
        });
        b67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b67ActionPerformed(evt);
            }
        });

        b31.setLocation(new java.awt.Point(3, 1));
        b31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b31MouseClicked(evt);
            }
        });

        b77.setLocation(new java.awt.Point(7, 7));
        b77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b77MouseClicked(evt);
            }
        });

        b42.setLocation(new java.awt.Point(4, 2));
        b42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b42MouseClicked(evt);
            }
        });

        b07.setLocation(new java.awt.Point(0, 7));
        b07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b07MouseClicked(evt);
            }
        });

        b52.setLocation(new java.awt.Point(5, 2));
        b52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b52MouseClicked(evt);
            }
        });

        b17.setLocation(new java.awt.Point(1, 7));
        b17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b17MouseClicked(evt);
            }
        });

        b62.setLocation(new java.awt.Point(6, 2));
        b62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b62MouseClicked(evt);
            }
        });

        b27.setLocation(new java.awt.Point(2, 7));
        b27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b27MouseClicked(evt);
            }
        });

        b72.setLocation(new java.awt.Point(7, 2));
        b72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b72MouseClicked(evt);
            }
        });

        b37.setLocation(new java.awt.Point(3, 7));
        b37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b37MouseClicked(evt);
            }
        });

        b02.setLocation(new java.awt.Point(0, 2));
        b02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b02MouseClicked(evt);
            }
        });

        b12.setLocation(new java.awt.Point(1, 2));
        b12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b12MouseClicked(evt);
            }
        });
/*
        b22.setLocation(new java.awt.Point(2, 2));
        b22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
        });

        b32.setLocation(new java.awt.Point(3, 2));
        b32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
        });
*/
       // b43.setText("O");
        b43.setBackground(Color.black);
        b43.setLocation(new java.awt.Point(4, 3));
        b43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b43MouseClicked(evt);
            }
        });

        b53.setLocation(new java.awt.Point(5, 3));
        b53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b53MouseClicked(evt);
            }
        });

        b63.setLocation(new java.awt.Point(6, 3));
        b63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b63MouseClicked(evt);
            }
        });

        b73.setLocation(new java.awt.Point(7, 3));
        b73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b73MouseClicked(evt);
            }
        });

        b03.setLocation(new java.awt.Point(0, 3));
        b03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b03MouseClicked(evt);
            }
        });

        b13.setLocation(new java.awt.Point(1, 3));
        b13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b13MouseClicked(evt);
            }
        });

        b23.setLocation(new java.awt.Point(2, 3));
        b23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b23MouseClicked(evt);
            }
        });

        b33.setBackground(Color.white);
       // b33.setText("O");
        b33.setLocation(new java.awt.Point(3, 3));
        /*
        b33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMouseClicked(evt);
            }
        });
*/
        b44.setBackground(Color.white);
       // b44.setText("O");
        b44.setLocation(new java.awt.Point(4, 4));
        b44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b44MouseClicked(evt);
            }
        });
        b44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b44ActionPerformed(evt);
            }
        });

        b54.setLocation(new java.awt.Point(5, 4));
        b54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b54MouseClicked(evt);
            }
        });

        b64.setLocation(new java.awt.Point(6, 4));
        b64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b64MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b00, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b01, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b02, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b03, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b04, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b05, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b06, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(b77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b07, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(b07, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(b77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(b06, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(b16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(b26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(b36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(b46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(b56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(b66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(b76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(b05, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(b15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(b25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(b35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(b45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(b55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(b65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(b75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(b04, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(b14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(b24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(b34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(b44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(b54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(b64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(b74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(b03, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(b02, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(b01, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(65, 65, 65)
                                        .add(b11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(b00, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(b70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 26, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void b00MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
        b01.setText("Hi");
        
    }                                

    private void b67ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void b44ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void b01MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b02MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b03MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b04MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b05ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void b05MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b06MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b07MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b10MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b11MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b12MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b13MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b14MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b15MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b16MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b17MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b20MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b21MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b22MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b23MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b24MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b25MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b26MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b27MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b30MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b31MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void bMouseClicked(java.awt.event.MouseEvent evt, int row, int col) {                                 
    	if(isvalid){
    	for(int i=0;i<8;i++){
    		for(int j=0;j<8;j++){
    			if(b.state[i][j]==0)
    				jb[i][j].setText("");
    		}
    	}
    	}
    	ArrayList<Disk> valid=new ArrayList<Disk>();
    	valid=b.validMove(color); //black
    	Disk move=new Disk(row,col,color);
        
    	if(have(valid,move)){
        isvalid=true;
       // jb[row][col].setForeground(color==1?Color.white:Color.black);
        jb[row][col].setBackground(color==1?Color.white:Color.black);
       // jb[row][col].setText("O");
        color=-color;//white
        b.add(move);
        b.update(move);
        printBoard(b.state);
        System.out.println();
        for(int i=0;i<8;i++){
        	for (int j=0;j<8;j++){
        		if(b.state[i][j]!=0){
        			jb[i][j].setBackground(b.state[i][j]==1?Color.white:Color.black);
        			//jb[i][j].setForeground(b.state[i][j]==1?Color.white:Color.black);
        		}
        	}
        }
        valid.clear();
        System.out.println(valid.isEmpty());
        valid=b.validMove(color);
        printDisk(valid);
        System.out.println();
        for (int i=0;i<valid.size();i++){
        	Disk disk=valid.get(i);
        	int r=disk.row;
        	int c=disk.col;
        	if(b.state[r][c]==0)
        	jb[r][c].setText("Valid");
        	jb[r][c].setForeground(color==1?Color.white:Color.black);
        }
        }
        else{
        	isvalid=false;
        	System.out.println("invalid");
        	JOptionPane pane = new JOptionPane("It's an invalid move");
        	pane.showMessageDialog(null,"Invalid move, try a different location");
        }
    	
      	
    	
    	
    } 
    
    
   

    private void b33MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b34MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b35MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b36MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b37MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b40MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b41MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b42MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b43MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b44MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b45MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b46MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b47MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b50MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b51MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b52MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b53MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b54MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b55MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b56MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b57MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b60MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b61MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b62MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b63MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b64MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b65MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b66MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b67MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b70MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b71MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b72MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b73MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b74MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b75MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b76MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void b77MouseClicked(java.awt.event.MouseEvent evt) {                                 
        // TODO add your handling code here:
    }                                
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton b00;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b03;
    private javax.swing.JButton b04;
    private javax.swing.JButton b05;
    private javax.swing.JButton b06;
    private javax.swing.JButton b07;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JButton b37;
    private javax.swing.JButton b40;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton b43;
    private javax.swing.JButton b44;
    private javax.swing.JButton b45;
    private javax.swing.JButton b46;
    private javax.swing.JButton b47;
    private javax.swing.JButton b50;
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JButton b53;
    private javax.swing.JButton b54;
    private javax.swing.JButton b55;
    private javax.swing.JButton b56;
    private javax.swing.JButton b57;
    private javax.swing.JButton b60;
    private javax.swing.JButton b61;
    private javax.swing.JButton b62;
    private javax.swing.JButton b63;
    private javax.swing.JButton b64;
    private javax.swing.JButton b65;
    private javax.swing.JButton b66;
    private javax.swing.JButton b67;
    private javax.swing.JButton b70;
    private javax.swing.JButton b71;
    private javax.swing.JButton b72;
    private javax.swing.JButton b73;
    private javax.swing.JButton b74;
    private javax.swing.JButton b75;
    private javax.swing.JButton b76;
    private javax.swing.JButton b77;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
